# Generated by Django 2.2 on 2019-04-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='书名')),
                ('publisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('writer', models.CharField(max_length=50, verbose_name='作者')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('book_stack', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstack.BookStack', verbose_name='书库')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
            },
        ),
    ]
