# Generated by Django 2.2 on 2019-04-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=40, verbose_name='供应商名')),
                ('book_stack', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstack.BookStack', verbose_name='书库')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
    ]
