# Generated by Django 2.2 on 2019-04-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='book_stack',
        ),
        migrations.CreateModel(
            name='SupplierStack',
            fields=[
                ('bookstack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookstack.BookStack')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name='所属供应商')),
            ],
            options={
                'verbose_name': '供应商书库',
                'verbose_name_plural': '供应商书库',
            },
            bases=('bookstack.bookstack',),
        ),
    ]
