# Generated by Django 2.2 on 2019-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('nick_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default=('male', '男'), max_length=6, verbose_name='性别')),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
