# Generated by Django 2.2 on 2019-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190430_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
    ]
