# Generated by Django 2.2 on 2019-04-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStack',
            fields=[
                ('stack_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='书库')),
            ],
            options={
                'verbose_name': '书库',
                'verbose_name_plural': '书库',
            },
        ),
    ]
